[package]
name = "jjss_tocargo"
version = "0.1.0"
edition = "2021"
authors = ["jjss <yjs@devtools.kr>"] # 작성자
repository = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
